/**
 * sidebar.mjs — apply docs/menu-config.json to the autogenerated docs sidebar.
 *
 * menu-config.json is authored in llm-d/llm-d and synced into docs/. It replaces
 * per-folder _category_.json and doc sidebar_position/sidebar_label frontmatter.
 */
import fs from 'node:fs';
import path from 'node:path';

const DOC_EXT = /\.(mdx?)$/i;
const SKIP_DIRS = new Set(['assets']);

/**
 * @param {string} configPath
 * @returns {{ categories: Record<string, object>, pages: Record<string, object> }}
 */
export function loadMenuConfig(configPath) {
  /** @type {{ categories?: Record<string, object>, pages?: Record<string, object> }} */
  let config = {};
  try {
    config = JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch (err) {
    // Missing file (e.g. before the first docs sync) -> empty config so the
    // sidebar falls back to pure autogeneration. Malformed JSON still fails loudly.
    if (err.code !== 'ENOENT') throw err;
  }
  return {
    categories: config.categories ?? {},
    pages: config.pages ?? {},
  };
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem[]} items
 * @returns {string[]}
 */
function collectDocIds(items) {
  /** @type {string[]} */
  const ids = [];
  for (const item of items) {
    if (item.type === 'doc') ids.push(item.id);
    else if (item.type === 'category' && item.items) ids.push(...collectDocIds(item.items));
  }
  return ids;
}

/**
 * Infer docs-relative directory for a category sidebar item.
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem} item
 * @returns {string | null}
 */
export function categoryDir(item) {
  if (item.type !== 'category') return null;

  if (item.link?.type === 'doc' && typeof item.link.id === 'string') {
    const id = item.link.id;
    if (id.endsWith('/index')) return id.slice(0, -'/index'.length);
    const slash = id.lastIndexOf('/');
    return slash >= 0 ? id.slice(0, slash) : id;
  }

  const docIds = collectDocIds(item.items ?? []);
  if (docIds.length === 0) return null;

  const parts = docIds.map((id) => id.split('/'));
  const minLen = Math.min(...parts.map((p) => p.length));
  /** @type {string[]} */
  const common = [];
  for (let i = 0; i < minLen - 1; i++) {
    const seg = parts[0][i];
    if (parts.every((p) => p[i] === seg)) common.push(seg);
    else break;
  }
  return common.join('/') || null;
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem} item
 * @param {Record<string, object>} categories
 */
function applyCategoryMeta(item, categories) {
  const dir = categoryDir(item);
  if (!dir) return item;
  const meta = categories[dir];
  if (!meta) return item;

  const out = { ...item };
  if (meta.label != null) out.label = meta.label;
  if (meta.collapsed != null) out.collapsed = meta.collapsed;
  if (meta.collapsible != null) out.collapsible = meta.collapsible;
  if (meta.className != null) out.className = meta.className;
  if (meta.link != null) out.link = meta.link;
  return out;
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem} item
 * @param {Record<string, object>} pages
 */
function applyPageMeta(item, pages) {
  if (item.type !== 'doc') return item;
  const meta = pages[item.id];
  if (!meta) return item;
  const out = { ...item };
  if (meta.label != null) out.label = meta.label;
  return out;
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem} item
 * @param {{ categories: Record<string, object>, pages: Record<string, object> }} config
 */
function getSortPosition(item, config) {
  if (item.type === 'category') {
    const dir = categoryDir(item);
    const pos = dir ? config.categories[dir]?.position : undefined;
    return typeof pos === 'number' ? pos : Number.POSITIVE_INFINITY;
  }
  if (item.type === 'doc') {
    const pos = config.pages[item.id]?.position;
    return typeof pos === 'number' ? pos : Number.POSITIVE_INFINITY;
  }
  return Number.POSITIVE_INFINITY;
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem} item
 */
function sortKey(item) {
  if (item.type === 'category') return (item.label ?? '').toLowerCase();
  if (item.type === 'doc') return (item.label ?? item.id ?? '').toLowerCase();
  return '';
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem[]} items
 * @param {{ categories: Record<string, object>, pages: Record<string, object> }} config
 */
function sortSiblings(items, config) {
  return [...items].sort((a, b) => {
    const pa = getSortPosition(a, config);
    const pb = getSortPosition(b, config);
    if (pa !== pb) return pa - pb;
    return sortKey(a).localeCompare(sortKey(b));
  });
}

/**
 * @param {import('@docusaurus/plugin-content-docs').SidebarItem[]} items
 * @param {{ categories: Record<string, object>, pages: Record<string, object> }} config
 */
export function applyMenuConfig(items, config) {
  const processed = items.map((item) => {
    if (item.type === 'category') {
      const patched = applyCategoryMeta(item, config.categories);
      return {
        ...patched,
        items: sortSiblings(applyMenuConfig(patched.items ?? [], config), config),
      };
    }
    return applyPageMeta(item, config.pages);
  });
  return sortSiblings(processed, config);
}

/**
 * The sidebar generator. Each docs version uses the menu-config.json in its own
 * content dir (versioned_docs/version-X/menu-config.json is frozen by
 * `docusaurus docs:version` at cut time), so menu changes on dev never reshape
 * a released version's sidebar. `menuConfig` (the dev docs/ config) is the
 * fallback for versions without a snapshot.
 *
 * @param {{ categories: Record<string, object>, pages: Record<string, object> }} menuConfig
 */
export function makeSidebarItemsGenerator(menuConfig) {
  /** @type {Map<string, ReturnType<typeof loadMenuConfig>>} */
  const byContentPath = new Map();
  const configFor = (contentPath) => {
    if (!contentPath) return menuConfig;
    if (!byContentPath.has(contentPath)) {
      const p = path.join(contentPath, 'menu-config.json');
      byContentPath.set(contentPath, fs.existsSync(p) ? loadMenuConfig(p) : menuConfig);
    }
    return byContentPath.get(contentPath);
  };
  return async function sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
    const items = await defaultSidebarItemsGenerator(args);
    return applyMenuConfig(items, configFor(args.version?.contentPath));
  };
}

/**
 * @param {string} dir
 * @param {string} docsDir
 * @param {string[]} out
 */
function walkCategoryDirs(dir, docsDir, out) {
  const rel = path.relative(docsDir, dir);
  if (rel && !rel.startsWith('..') && !SKIP_DIRS.has(path.basename(dir))) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    const subdirs = entries.filter((e) => e.isDirectory());
    const docs = entries.filter(
      (e) => e.isFile() && (e.name.endsWith('.md') || e.name.endsWith('.mdx')),
    );
    if (subdirs.length > 0 || docs.length > 1) {
      out.push(rel.split(path.sep).join('/'));
    }
    for (const sub of subdirs) {
      walkCategoryDirs(path.join(dir, sub.name), docsDir, out);
    }
  }
}

/**
 * @param {string} docId
 * @param {string} docsDir
 */
function docExists(docId, docsDir) {
  for (const ext of ['.md', '.mdx']) {
    if (fs.existsSync(path.join(docsDir, docId + ext))) return true;
  }
  if (fs.existsSync(path.join(docsDir, docId, 'index.md'))) return true;
  if (fs.existsSync(path.join(docsDir, docId, 'index.mdx'))) return true;
  return false;
}

/**
 * @param {{ categories: Record<string, object>, pages: Record<string, object> }} config
 * @param {string} docsDir
 * @param {{ warn?: (msg: string) => void }} [opts]
 */
export function validateMenuConfig(config, docsDir, opts = {}) {
  const warn = opts.warn ?? ((msg) => console.warn(`[menu-config] ${msg}`));

  /** @type {string[]} */
  const categoryDirs = [];
  walkCategoryDirs(docsDir, docsDir, categoryDirs);

  for (const key of Object.keys(config.categories)) {
    const dirPath = path.join(docsDir, ...key.split('/'));
    if (!fs.existsSync(dirPath)) {
      warn(`orphan category key "${key}" — directory does not exist`);
    }
  }

  for (const key of Object.keys(config.pages)) {
    if (!docExists(key, docsDir)) {
      warn(`orphan page key "${key}" — doc file does not exist`);
    }
  }

  for (const dir of categoryDirs) {
    if (!config.categories[dir]) {
      warn(`missing category config for "${dir}"`);
    }
  }
}
